INSERT INTO COMMON_ENUM (NAME,CODE,READ_ONLY) VALUES ('监控分组','MONITOR_GROUP',1);
ALTER TABLE T_INTERFACE ADD COLUMN monitorGroup VARCHAR(255);
ALTER TABLE T_MONITOR_STATUS ADD COLUMN monitorGroup VARCHAR(255);
ALTER TABLE T_MONITOR_STATUS ADD COLUMN interfaceCode VARCHAR(255);